#!/bin/bash
docker run --rm kaczmarj/neurodocker generate \
--base ubuntu:xenial-20161213 --pkg-manager apt \
--install git vim \
--afni version=latest \
--ants version=2.2.0 \
--freesurfer version=6.0.0 min=false \
--fsl version=5.0.10 \
--user=neuro \
--user=root \
--mrtrix3 \
--neurodebian os_codename="jessie" \
              download_server="usa-nh" \
              pkgs="dcm2niix git-annex-standalone" \
--user=neuro \
--miniconda env_name=default \
            python_version=3.5.1 \
            conda_opts="--channel vida-nyu" \
            conda_install="numpy scipy matplotlib pandas reprozip traits jupyter" \
            pip_install="nipype" \
--miniconda env_name=py27 \
            python_version=2.7 \
            add_to_path=false \
--expose 8888 \
--user=root \
--instruct="RUN apt-get update &&  \
	    apt-get install -y zsh wget" \
--instruct="RUN apt-get install -y npm nodejs-legacy &&  \
	    rm -rf /tmp/* /etc/apk/cache/*" \
--instruct="RUN npm install -g configurable-http-proxy"  \
--user=neuro \
--instruct="ENV SHELL /bin/zsh" \
--workdir /home/neuro \
--no-check-urls > Dockerfile

cat Dockerfile.2 >> Dockerfile
